---
- name: Install sensor client for raspberry pi
  hosts: pi
  vars:
    ansible_ssh_user: pi
  tasks:
  - name: Enable hardware SPI
    become: yes
    lineinfile: 
      dest: /boot/config.txt
      regexp: dtparam=spi=on
      line: dtparam=spi=on
      state: present
    notify:
      - restart
  - meta: flush_handlers
  - name: Checkout Pi4J
    git:
      repo: 'https://github.com/Pi4J/pi4j.git'
      dest: "{{ ansible_env.HOME}}/Pi4J"
      force: yes
  handlers:
  - name: Restart Pi
    become: yes
    command: /sbin/shutdown -r +1
    async: 0
    poll: 0
    ignore_errors: true
    listen: restart
  - name: Wait for Pi to boot
    local_action: wait_for host={{ inventory_hostname }} 
      state=started 
      port=22 
      delay=80 
      timeout=300 
      connect_timeout=15
    listen: restart
...
