---
- name: Run sensor client on raspberry pi
  hosts: all
  vars:
    ansible_ssh_user: pi
  tasks:
  - name: Copy template
    template:
      src: .habarama.json.j2
      dest: "{{ ansible_env.HOME}}/.habarama.json"
  - name: Run client on background
    shell: nohup python plant.py &
    args:
      chdir: "{{ ansible_env.HOME}}/Hogarama/Habarama/PI/python-mqtt"
    environment:
      SENSOR_NAME: "{{SENSOR_NAME}}"
      SENSOR_TYPE: "{{SENSOR_TYPE}}"
      SENSOR_LOCATION: "{{SENSOR_LOCATION}}"
...
