apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: 2017-10-12T08:27:13Z
    labels:
      app: hogarama-jenkins
    name: hogarama-jenkins
    namespace: hogarama-buildserver
    resourceVersion: "7398"
    selfLink: /api/v1/namespaces/hogarama-buildserver/persistentvolumeclaims/hogarama-jenkins
    uid: 25eee479-af27-11e7-b683-9a46b233a9bd
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    volumeName: pv0025
  status:
    accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
    capacity:
      storage: 100Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: 2017-10-12T08:27:38Z
    name: maven-repo
    namespace: hogarama-buildserver
    resourceVersion: "7442"
    selfLink: /api/v1/namespaces/hogarama-buildserver/persistentvolumeclaims/maven-repo
    uid: 351a276c-af27-11e7-b683-9a46b233a9bd
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    volumeName: pv0091
  status:
    accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
    capacity:
      storage: 100Gi
    phase: Bound
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
