kind: "Template"
apiVersion: "v1"
metadata:
  name: "hogarama-jenkins"
  annotations:
    openshift.io/display-name: "Jenkins (Hogarama)"
    description: "Jenkins Service for building and testing the Hogarama project"
    iconClass: "icon-jenkins"
    tags: "instant-app,jenkins"

parameters:
  - name: "JENKINS_SERVICE_HOST"
    displayName: "Jenkins service name"
    value: "jenkins"
    required: true

  - name: "JNLP_SERVICE_NAME"
    displayName: "Jenkins service name"
    value: "jenkins-jnlp"
    required: true

  - name: "GIT_REPO_URL"
    displayName: "Hogarama git repository url (use https:// instead of git://)"
    value: "https://github.com/Gepardec/Hogarama.git"
    required: true

  - name: "GIT_REPO_REF"
    displayName: "Hogarama branch"
    value: "JENKINS_CHANGES"
    required: true

  - name: "KUBERNETES_MASTER"
    displayName: "The url to the openshift instance. (E.g.: https://192.168.42.195:8443)"
    value: "https://192.168.42.195:8443"
    required: true

  - name: "JENKINS_SLAVE_IMAGE_MAVEN"
    displayName: "The docker tag for the maven slave image"
    value: "gdhet/hogarama-jenkins-slave-maven-rhel7-docker:3.5.0-jdk-8u144b01"
    required: true

  - name: "JENKINS_FILE"
    displayName: "The Jenkinsfile for the build"
    value: "buildserver/Jenkinsfile"
    required: true

objects:
  - kind: "ServiceAccount"
    apiVersion: "v1"
    metadata:
      name: "${JENKINS_SERVICE_HOST}"
      annotations:
        serviceaccounts.openshift.io/oauth-redirectreference.jenkins: "{\"kind\":\"OAuthRedirectReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"Route\",\"name\":\"${JENKINS_SERVICE_HOST}\"}}"

  - kind: "PersistentVolumeClaim"
    apiVersion: "v1"
    metadata:
      name: "${JENKINS_SERVICE_HOST}"
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "1Gi"

  - kind: "RoleBinding"
    apiVersion: "v1"
    metadata:
      name: "${JENKINS_SERVICE_HOST}_edit"
    groupNames: null
    subjects:
      - name: "${JENKINS_SERVICE_HOST}"
        kind: "ServiceAccount"
    roleRef:
      name: "edit"

  - kind: "ImageStream"
    apiVersion: "v1"
    metadata:
      name: "${JENKINS_SERVICE_HOST}"
      labels:
        application: "${JENKINS_SERVICE_HOST}"

  - kind: "BuildConfig"
    apiVersion: "v1"
    metadata:
      name: "${JENKINS_SERVICE_HOST}"
      labels:
        application: "${JENKINS_SERVICE_HOST}"
    spec:
      source:
        type: "Git"
        git:
          uri: "${GIT_REPO_URL}"
          ref: "${GIT_REPO_REF}"
        contextDir: "buildserver/s2i/jenkins-ci"
      strategy:
        type: "Source"
        sourceStrategy:
          from:
            kind: "ImageStreamTag"
            namespace: "openshift"
            name: "jenkins:2"
          secrets:
            - secret: "sshbuildsecret"
      output:
        to:
          kind: "ImageStreamTag"
          name: "${JENKINS_SERVICE_HOST}:latest"
      triggers:
        - type: "ImageChange"
          imageChange:

  - kind: "DeploymentConfig"
    apiVersion: "v1"
    metadata:
      name: "${JENKINS_SERVICE_HOST}"
      annotations:
        template.alpha.openshift.io/wait-for-ready: "true"
    spec:
      strategy:
        type: "Recreate"
      replicas: "1"
      selector:
        name: "${JENKINS_SERVICE_HOST}"
      triggers:
        - type: "ImageChange"
          imageChangeParams:
            automatic: true
            containerNames:
              - "${JENKINS_SERVICE_HOST}"
            from:
              kind: "ImageStreamTag"
              name: "${JENKINS_SERVICE_HOST}:latest"
        - type: "ConfigChange"
      template:
        metadata:
          labels:
            name: "${JENKINS_SERVICE_HOST}"
        spec:
          serviceAccountName: "${JENKINS_SERVICE_HOST}"
          containers:
            - name: "${JENKINS_SERVICE_HOST}"
              image: " "
              readinessProbe:
                timeoutSeconds: 1
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 6
                httpGet:
                  path: "/login"
                  port: 8080
              livenessProbe:
                timeoutSeconds: 1
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 6
                httpGet:
                  path: "/login"
                  port: 8080
              env:
                - name: "JNLP_SERVICE_NAME"
                  value: "${JNLP_SERVICE_NAME}"
                - name: "KUBERNETES_TRUST_CERTIFICATES"
                  value: "true"
                - name: "GIT_REPO_URL"
                  value: "${GIT_REPO_URL}"
                - name: "GIT_REPO_REF"
                  value: "${GIT_REPO_REF}"
                - name: "OPENSHIFT_JENKINS_JVM_ARCH"
                  value: "x86_64"
                - name: "OPENSHIFT_ENABLE_OAUTH"
                  value: "true"
                - name: "OPENSHIFT_ENABLE_REDIRECT_PROMPT"
                  value: "true"
                - name: "JENKINS_FILE"
                  value: "${JENKINS_FILE}"
                - name: "GIT_SSL_NO_VERIFY"
                  value: "true"
              resources:
                limits:
                  memory: "4096Mi"
                  cpu: "2000m"
              volumeMounts:
                - name: "${JENKINS_SERVICE_HOST}"
                  mountPath: "/var/lib/jenkins"
              terminationMessagePath: "/dev/termination.log"
              imagePullPolicy: "IfNotPresent"
              capabilities:
                securityContext:
                  capabilities:
                    privileged: false
          volumes:
            - name: "${JENKINS_SERVICE_HOST}"
              persistentVolumeClaim:
                claimName: ${JENKINS_SERVICE_HOST}

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      name: "${JENKINS_SERVICE_HOST}"
      annotations:
        template.openshift.io/expose-uri: "http://{.spec.host}{.spec.path}"
    spec:
      to:
        kind: "Service"
        name: "${JENKINS_SERVICE_HOST}"
      tls:
        termination: "edge"
        insecureEdgeTerminationPolicy: "Redirect"

  - kind: "Service"
    apiVersion: "v1"
    metadata:
      name: "${JENKINS_SERVICE_HOST}"
      annotations:
        service.alpha.openshift.io/dependencies: "[{\"name\": \"${JNLP_SERVICE_NAME}\", \"namespace\": \"\", \"kind\": \"Service\"}]"
        service.openshift.io/infrastructure: "true"
    spec:
      ports:
        - name: "web"
          protocol: "TCP"
          port: 80
          targetPort: 8080
          nodePort: 0
      selector:
        name:  "${JENKINS_SERVICE_HOST}"
      type: "ClusterIP"
      sessionAffinity: "None"

  - kind: "Service"
    apiVersion: "v1"
    metadata:
      name: "${JNLP_SERVICE_NAME}"
    spec:
      ports:
        - name: "agent"
          protocol: "TCP"
          port: 50000
          targetPort: 50000
          nodePort: 0
      selector:
        name:  "${JENKINS_SERVICE_HOST}"
      type: "ClusterIP"
      sessionAffinity: "None"
