kind: "ImageStreamList"
apiVersion: "v1"
items:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: "hogarama-jenkins"
      annotations:
        openshift.io/display-name: "hogarama-jenkins"
    spec:
      tags:
        - name: latest
          annotations:
            openshift.io/display-name: "hogarama-jenkins"
            iconClass: "icon-jenkins"
            tags: "hogarama"
            version: "latest"
          from:
            kind: "DockerImage"
            name: "gepardec/hogarama-jenkins"

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: "hogarama-jenkins-slave-maven"
      annotations:
        openshift.io/display-name: "hogarama-jenkins-slave-maven"
      labels:
        role: "jenkins-slave"
    spec:
      tags:
        - name: latest
          annotations:
            openshift.io/display-name: "hogarama-jenkins-slave-maven"
            tags: "hogarama-jenkins-slave-maven"
            version: "latest"
          from:
            kind: "DockerImage"
            name: "gdhet/hogarama-jenkins-slave-maven-rhel7-docker"

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: "hogarama-jenkins-slave-oracle"
      annotations:
        openshift.io/display-name: "hogarama-jenkins-slave-oracle"
      labels:
        role: "jenkins-slave"
    spec:
      tags:
        - name: latest
          annotations:
            openshift.io/display-name: "hogarama-jenkins-slave-oracle"
            tags: "hogarama-jenkins-slave-oracle"
            version: "latest"
          from:
            kind: "DockerImage"
            name: "gdhet/hogarama-jenkins-slave-oracle-rhel7-docker"

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: "hogarama-fluentd"
      annotations:
        openshift.io/display-name: "hogarama-fluentd"
    spec:
      tags:
        - name: latest
          annotations:
            openshift.io/display-name: "hogarama-fluentd"
            tags: "hogarama-fluentd"
            version: "latest"
