apiVersion: v1
items:
  - apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata:
      name: "maven-repo"
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "5Gi"
      volumeName: "pv0001"
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
