swagger: '2.0'
info:
  version: 1.0.0
  title: Hogarama
  description: A swagger-2.0 API-specification for Hogarama
  termsOfService: 'http://helloreverb.com/terms/'
  contact:
    name: Gepardec IT Services GmbH
    email: office@gepardec.com
    url: 'http://www.gepardec.com/'
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
host: localhost
basePath: /hogajama-rs/rest
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /sensor:
    get:
      description: Returns all sensor-names
      operationId: getAllSensors
      produces:
        - application/json
      responses:
        '200':
          description: sensor names response
          schema:
            type: array
            items:
              type: string
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /sensor/allData:
    get:
      description: Returns all sensors
      operationId: 'getAllData({maxNumber})'
      parameters:
        - in: query
          name: maxNumber
          type: integer
          required: false
          description: Maximum number of sensor data entries
        - in: query
          name: sensor
          type: string
          required: false
          description: Sensorname for which data should be shown
      produces:
        - application/json
      responses:
        '200':
          description: sensor data response
          schema:
            type: array
            items:
              $ref: '#/definitions/sensorData'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  sensorData:
    type: object
    required:
      - id
      - time
      - sensorName
      - type
      - value
      - location
      - version
    properties:
      id:
        type: string
      time:
        type: string
        format: date
      sensorName:
        type: string
      type:
        type: string
      value:
        type: number
        format: double
      location:
        type: string
      version:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
